### ISSUE TITLE
daplink firmware v254 MSD and Web features not working as expected

### ISSUE THREAD

**Issue by mike-bradley** [MDK-Packs/IMXRT1050-EVKB_BSP#1]
After updating an IMXRT1050-EVBK (sch-30168 rev A1) to either of the v254 DAPLink FW (hyper and qspi versions tested), I was no longer able to copy the mbed blinky program to the MSD drive letter in windows.  I am using a separate supply to J9, and J1 set to 3-4.  The download started, but seemed to cause the board to disconnect and reconnect.  FAIL.TXT file reports 'The interface firmware FAILED to initialize the target MCU'.  Details.txt files for board with 244 and 254 FW versions attached.
[DETAILS.TXT](https://github.com/MDK-Packs/IMXRT1050-EVKB_BSP/files/7352335/DETAILS.TXT)
[detail_254.TXT](https://github.com/MDK-Packs/IMXRT1050-EVKB_BSP/files/7352390/detail_254.TXT)
Rolling back to DAPLink FW 244 and the same mbed blinky file downloads and runs as expected.

Within the web based Keil studio, I see this for the board, so looks like the Web driver feature in the new v254 driver isn't working and looks it's not fully supported for direct bin file download/debug from the browser.
![image](https://user-images.githubusercontent.com/39832313/137465644-9bd84ace-5d3b-4b93-a409-7ff9fc459300.png)
This in the latest version of MS Edge and Chrome.  The Web USB: CMSIS-DAP part of composite device looks to be good (no warning triangle) in Device Manager.

**Comment by KeilChris** [comment]
[Blinky.EVKB-IMXRT1050_MDK.bin.zip](https://github.com/MDK-Packs/IMXRT1050-EVKB_BSP/files/7353334/Blinky.EVKB-IMXRT1050_MDK.bin.zip)
Can you try to drag and drop this bin file, please (unzip first)?

**Comment by mike-bradley** [comment]
unzipped, and downloaded with DAPLink 254 FW, and same fail.txt error.  The main CPU is being reset and is running whatever FW image is left in the Hyperflash.  (I put in a non-blinky fw image with v244 ) and I get the output for that FW after trying to download the .bin with v254.
If I download the MDK.bin you provided with v244, it downloads and replaces the non-blinky FW with no issue.

**Comment by mike-bradley** [comment]
Hi Chris, will do.  I certainly appreciate all the quick responses to try and get this up and running.
